name: Hello World Workflow

on:
  push:
  workflow_call:  # Makes this workflow reusable

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
